name: noaa-gridded3
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.11.*
  - scipy
  - cartopy
  - netcdf4
  - cell_tree2d
  - six
  - pytest
  - matplotlib
  - jupyter
  - nb_conda_kernels
#  - pip: 
#    - "--editable=git+http://github.com/NOAA-ORR-ERD/gridded@scipy2017#egg=scipy2017"
